### PR TITLE
4.15.0

### PR DESCRIPTION
**Pull request by Geniy83**
corrected NightPost.html (added port). Thanks

### CODE REVIEW

**Comment by j-kaltes** [comment]
You don't translate _hostname_ and _port_. Is the untranslated version more widely known in Belarus?

**Comment by Geniy83** [comment]
Yes. Some words are best left untranslated. People with diabetes in Belarus will understand them better

**Comment by Geniy83** [comment]
Hello. Please tell me the meaning of this line of code "96   <string name="ringshort">Ring</string>" in strings.xml. Need to understand in order to translate correctly

**Comment by j-kaltes** [comment]
strings.xml doesn't contain "96 Ring". It does contain ` <string name="ringshort">Ring</string>`
ringshort is a short name for Ringtone, used in the WearOS version of Juggluco.

**Comment by Geniy83** [comment]
Yes, that's what I meant. Why That <string name="ring short">Ring</string> was not inserted when sending the message. Thank you

**Pull request merged**
