### PR TITLE
be-BY

### PR DESCRIPTION
**Pull request by Geniy83**
Hello. I added a translation into Belarusian (today or tomorrow I will add more strings.xml and jugglucotext.cpp). I will also immediately translate into Ukrainian. Please add this translation to yourself. Thank you for the work you've done. Very good app!!! Many in Belarus and Ukraine use Juggluco

### CODE REVIEW

**Comment by j-kaltes** [comment]
Thank you for your contribution. I put the helpfiles in an apk: https://drive.google.com/file/d/1TofJCPVPumw-7l_MdqPS8LbF4voNZcCI/view?usp=share_link Did you already make an APK containing your translation?
When strings.xml jugglucotext.cpp are ready we have to look if everything is ok. I already saw a small mistake:
In  NightPost.html port is missing after hostname in "URL: URL павінен быць у форме https://hostname: напрыклад, https://myname.herokuapp.com:6789" .  And cgm-remote-monitor should contain a link, but not https://hostname.

What is exactly your language background, that you know both Belarusian and Ukrainian.

**Comment by Geniy83** [comment]
I haven't made my APK yet, thanks for making the APK. I'm more of a web developer (Java). Thank you for finding the errors, I'll fix NightPost.html tomorrow.

Belarusian and Ukrainian languages are very similar. Dmitry also helps me with translation from Ukraine. I did not want to translate into Russian....

Thanks again for a well written app!

**Comment by Geniy83** [comment]
I can speak Belarusian, Ukrainian, Russian and English well )))

**Comment by Geniy83** [comment]
Where you can have a conversation with you when questions arise about the work of Juggluco?

**Comment by j-kaltes** [comment]
Here or you can e-mail to jaapkorthalsaltes@gmail.com or with whatever other method you know of.

**Comment by Geniy83** [comment]
Hello Jaap Korthals Altes. We already know each other, I was translating
Juggluco into Belarusian and Ukrainian.
I want to ask you for help. Please explain to me how you decrypt the data
received from Libre 2? Did you decompile the LibreLink apk and use it or
something else?
I'll try to explain to you why I need this. I want to write an application
for resetting the sensor, as the Pole Marek Macner did with Libre 1 (
https://github.com/MarekM60) by writing the eDroplet application. Can you
help me by explaining how data encryption occurs?
Thanks for understanding.

пн, 15 мая 2023 г., 13:16 Jaap Korthals Altes ***@***.***>:

**Comment by j-kaltes** [comment]
Where did you hear that eDroplet extends the life of Libre 1 sensors? The only mention that I can find is this:
https://github.com/JoernL/LimiTTer/issues/13#issuecomment-1650071934
And it says that it doesn't work. 
It does scan some old Libre 0 and Libre 2 sensors. For some showing Sensor data (C5 09 30 01 03 19 00 ....) for others the Sensor ID. For a Libre 2 sensor I plan to return, it gets the right activation time, but the minutes sensor life are wrong it says 12372 minutes, but the sensor ends 5 november at 20:43, that is only 5 days from now, 12372 minutes is more than 8 days.
I don't see why the decrypted content of the NFC scan would bring you any further, but you can find it in Juggluco. After executing ProcessOne in nfcdata ( https://github.com/j-kaltes/Juggluco/blob/2880bbaf61bf8cc1d1e380caf022f12fdb1dc753/Common/src/main/cpp/g.cpp#L230C43-L230C43), datptr points to the decrypted content of the scan.

**Comment by Geniy83** [comment]
eDropletNFC can reset the Libre 1 sensor, assigning it status 01 (like a
new sensor) and then you need to activate the sensor again. I myself use
this application to extend the life of Libre 1. I can send you the apk file
of its different versions). And you can check how it works on Libre 1. The
eDropletNFC application does not work with Libre 2.
I want to do this - reset the sensor, assigning it the status of a new
sensor, and then I can activate it again as a new one, for example with the
Juggluco program. But in order for the Libre 2 sensor to understand the
command to reset, it must be encoded back and sent to it.

вт, 31 окт. 2023 г., 13:07 Jaap Korthals Altes ***@***.***>:

**Comment by j-kaltes** [comment]
Knowing the decrypted content will not help you further.
I tried https://github.com/MarekM60/eDroplet/releases/download/0.1/eDroplet_0_1.apk

**Pull request merged**
