### PR TITLE
Changing the translation

### PR DESCRIPTION
**Pull request by Geniy83**
Added translation talkhelp.html;
Changed _Mirror_ translation to _Clone_;
Left without translation _Dark mode_.
There is no need to build APK now, I am making changes to strings.xml and bejugglucotext.cpp

### CODE REVIEW

**Comment by Geniy83** [comment]
I've made changes to the Jugglucohelp to match our translation conventions and ask you to add those changes and build the APK. I don't want to remove the fork. Or maybe I misunderstood you?
Can you build an APK with these changes for me? Thank you

**Comment by Geniy83** [comment]
_strings.xml and bejugglucotext.cpp_ I saw that you yourself have already changed

**Comment by j-kaltes** [comment]
"Talk" and related words are not translated.

**Comment by Geniy83** [comment]
Now I understand). Then please do not include in the changes _talkhelp.html_.

**Comment by j-kaltes** [comment]
Why leave out talkhelp.html? If you include it, you can see how it is presented.

**Comment by j-kaltes** [comment]
What about:
```
<string name="speed">Хуткасць</string>
  <string name="pitch">Крок</string>
  <string name="talker">Голас</string>
  <string name="secondsbetween">Секунд паміж</string>
  <string name="test">Тэст</string>
```

Talk -> Размаўляць

**Comment by j-kaltes** [comment]
No, you translated pitch with Вышыня.

**Comment by j-kaltes** [comment]
Here is a phone apk with these changes: https://drive.google.com/file/d/1ng_02GB3ppxkbV_Zme8NtAVvgOlg427k/view?usp=share_link

**Comment by Geniy83** [comment]
> Как насчет:
> 
> ```
> <string name="speed">Хуткасць</string>
>   <string name="pitch">Крок</string>
>   <string name="talker">Голас</string>
>   <string name="secondsbetween">Секунд паміж</string>
>   <string name="test">Тэст</string>
> ```
> 
> Обсуждение -> Размаўляць
Yes, it must be enabled. I'm sorry I didn't understand you

**Comment by j-kaltes** [comment]
Does talk work with Belarusian on your phone? My phones talk English when I set the language to Belarusian.

**Comment by Geniy83** [comment]
I'll test it later and get back to you. Forgive me for misunderstanding you when communicating... (((

**Comment by Geniy83** [comment]
There is a question. Version 4.17.3 when I installed the Belarusian language was loaded into the system but was not the main one, and in this version Juggluco was in Belarusian. And in versions 4.17.4, in order for Juggluco to be in Belarusian, I need to make Belarusian the main language in the system, which is not very convenient. Can I return it as it was in version 14.7.3?

**Comment by j-kaltes** [comment]
I don't understand. I have not changed anything in this regard. Juggluco takes over the language of the system, Except that in Android 13, you can specify the language for a particular app. Juggluco never behaved in another way.

**Comment by Geniy83** [comment]
I tried all versions 4.17.4 that you sent me, it happens to everyone. And in all versions 4.17.3, I do not need to make Belarusian the main language in the system

**Comment by Geniy83** [comment]
I have Android 12

**Comment by j-kaltes** [comment]
Also version 4.17.3 takes over the system language. That they way it should behave. 
Set the system language to another language than English, to test it out or kill the app and start it again.
Version 4.17.3 contains a bug that it assumes it has the language it was started with, also after switching to another language. So it doesn't switch back to the language it was started with because it thinks it already uses that langauge.

**Comment by Geniy83** [comment]
I have now removed English from the system, set Russian as the main language, Belarusian is loaded. I open Juggluco and it is in English. Then I make the Belarusian language the main language in the system and Juggluco immediately became in the Belarusian language. This is me about version 4.17.4

**Comment by j-kaltes** [comment]
That is how it should work. English is the default, thus used for Russian.
Juggluco doesn't have to posibility to specify a different langauge than the system language. Why should an ordinary user want that?

**Comment by Geniy83** [comment]
We have two languages in Belarus. Some Russian some Belarusian (they are similar). And the users in the system have the main language installed, some have Russian, the second have Belarusian. Then whoever has the main language in the Russian system installed, then their Juggluco will be in English by default.

**Comment by j-kaltes** [comment]
Change the system language to Belarusian and the in-app language setting of other apps to Russian.

**Pull request merged**
